Update docs for refactor branch
fosscord/fosscord-docs pull request #44
Opened 2022-12-28 09:58 UTC by MaddyUnderStars

### This PR is not ready yet.

This PR rewrites everything from the ground up with hopefully more detail everywhere for the fosscord-server maddy/refactor branch. These docs should go live when the maddy/refactor branch is made default instead of staging.

I would absolutely love feedback on anything regarding these!

2023-01-05 10:15 UTC, TheArcaneBrony requested changes
Needs some work, looks good otherwise!

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/security/limits.md
> +# Rate Limiting
TODO: write documentation?

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/security/regTokens.md
> +# Registration Tokens
TODO: write documentation?

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/security/rights.md
> +| `OPERATOR`                | 1 << 0  | All rights                                                                                                                                            |
Clarify this includes shutdown

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/systemd.md
> +```ini
TOML?

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/systemd.md
> +# Systemd
Where's muh OpenRC???? /j

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/systemd.md
> +Make sure to edit the file as needed, such as replacing the user.
DO NOT RUN AS ROOT PLEASE IF YOU MUST JUST MAKE A SERVICE ACCOUNT KTHX

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/systemd.md
> +To view the server logs, you may use `journalctl -u fosscord.service`, or with `-f` to view them as they come.
lnav?
`journalctl -xefu fosscord | lnav` gives nice scrollable, colorized and searchable log view.

Also, .service isnt needed yknow

2023-01-05 10:15 UTC, TheArcaneBrony commented on docs/setup/server/updating.md
> +!!! error "Do not run `npm run sync:db` with existing databases! You may suffer dataloss!"
Remove this, also Dataless822 returns!

2023-01-05 14:55 UTC, erkinalp requested changes

2023-01-05 14:55 UTC, erkinalp commented on docs/contributing/conduct.md
> +By contributing to any Fosscord projects (for example, through pull request) you guarantee that you have the rights to resign all rights to Fosscord under the AGPLV3 license.
```suggestion
By contributing to any Fosscord projects (for example, through pull request) you guarantee that you have the requisite rights to grant Fosscord a AGPLV3 licence. If your work is legally in the public domain (through a legally accepted waiver or a mandate (such as the national government works of United States, People's Republic of China and Israel), you **must** declare this.
```

2023-01-05 15:43 UTC, Puyodead1 commented on docs/setup/server/Test Client/plugins.md
> +quite easily with only slight modifications to the [user script](https://github.com/Vendicated/Vencord#installing-on-browser).
You should also have to modify the `match` meta option, or it will only work on discord.

2023-01-05 15:43 UTC, Puyodead1 commented on docs/setup/server/configuration/guildFeatures.md
> +A list of all available guild features is available [here](https://gist.github.com/Techy/ecc60b12e94f8fc8185f09b82aa91dd2)
Just a note, the linked gist of guild features is outdated and doesn't appear to get updated. Something like https://github.com/Delitefully/DiscordLists#guild-feature-glossary might be better.

2023-01-05 15:43 UTC, Puyodead1 commented on docs/setup/server/database.md
> +but to configure Fosscord to use your new, shiny database, simply set the `DATABASE` [environment variable](configuration/env.md)
```suggestion
but to configure Fosscord to use your shiny new database, simply set the `DATABASE` [environment variable](configuration/env.md)
```
The comma/wording seems a little odd imo

2023-01-05 15:43 UTC, Puyodead1 commented on docs/setup/server/index.md
> +-   On Windows: [Visual Studio](https://visualstudio.microsoft.com/) (**NOT** VSCode) with the `Desktop development with C++` package.
Visual studio build tools is also an option, as the full blown IDE might not be required in all cases.
> These Build Tools allow you to build Visual Studio projects from a command-line interface.

2023-01-05 15:43 UTC, Puyodead1 commented on docs/setup/server/reverseProxy.md
> +Afterwhich, you should now have a SSL secured Fosscord instance!
```suggestion
After which, you should now have an SSL secured Fosscord instance!
```
`After which` should be 2 separate words according to my expert research. 😄

2023-01-05 15:43 UTC, Puyodead1 commented on docs/setup/server/reverseProxy.md
> +But wait! There's more, actually. If you have changed your `gateway_endpointPublic`
```suggestion
But wait! There's more! If you have changed your `gateway_endpointPublic`
```
The `actually` here sounds odd in a sentence?

2023-01-05 15:43 UTC, Puyodead1 commented on docs/setup/server/updating.md
> +Thus, you can update the server by running `git pull`.
```suggestion
Thus, you can update the server by running `git pull` in the `fosscord-server` directory.
```
wHeRe dO i RuN tHe CoMmAnd?? iT nO wOrK.
never know, someone might try to run it from another directory if they don't know what git is.

2023-01-06 01:59 UTC, MaddyUnderStars commented on docs/setup/server/configuration/embeds.md
> +Once you have your API key, set the `external_twitter` [config](index.md) value to your API key, wrapped in quotes.
can't create an alt to do this, as they lock developer accounts behind a verified phone number. Can someone else check?

2023-01-06 02:21 UTC, MaddyUnderStars commented on docs/setup/server/index.md
> +If all went according to plan, you can now access your new Fosscord instance at [http://localhost:3001](http://localhost:3001)! Congrats!
If they did it on a remote system they probably can't access the instance without nginx for example anyway. Other guides for things like rabbitmq don't really account for this, so I think it's fine

2023-01-06 02:38 UTC, MaddyUnderStars commented on docs/setup/server/security/rights.md
> +| `OPERATOR`                | 1 << 0  | All rights                                                                                                                                            |
todo: write documentation of the routes available to operators.

also: operator probably shouldn't be the right used for shutdown and other admin tasks. specific rights for those purposes should be made.

2023-01-06 02:43 UTC, MaddyUnderStars commented on docs/contributing/conduct.md
> +-   Accepting responsibility and apoligising to those affected for our mistakes.
sorry for being australian :sob:

2023-01-07 08:08 UTC, erkinalp approved these changes

2023-01-07 11:39 UTC, MaddyUnderStars commented
With that, I'd say these docs are at a pretty acceptable level at the moment. If anyone has any additional pages they'd like to see added, I'd love to hear about it.

2023-01-07 13:03 UTC, MaddyUnderStars commented
For the contributing section of the docs, do we think it's a good idea to just use something like jsdoc to generate it for us? I had done some playing around with it earlier today and it seemed alright, I think. At least, better than what we had before (and anything I could write, tbh)

2023-01-07 21:05 UTC, erkinalp approved these changes

2023-01-08 07:18 UTC, erkinalp requested changes

2023-01-08 07:18 UTC, erkinalp commented on docs/contributing/index.md
> +    Additionally, please do not try to snipe features that others are working on.
```suggestion
-   Try to keep each commit to a single feature or idea, with descriptions of what it is and why it is done. No "Large refactor" commits that touch every file, unless absolutely required due to the nature of change.
-   Leave comments in your code about why something is done when appropriate, not just what it is doing.
-   If you're working on a feature, please announce that you're working on it (in the relevant GH issue or our Discord, preferably both), so that we can work more effectively and minimise conflicting change attempts.
    Additionally, please do not try to snipe features that others are working on.
```

2023-01-08 07:18 UTC, erkinalp commented on docs/contributing/index.md
> +Discords does not document anything that is not related to application/bot development, though.
```suggestion
Discords generally does not document anything that is not related to application/bot development, though.
```

2023-01-08 18:19 UTC, erkinalp approved these changes

2023-01-09 13:36 UTC, TheArcaneBrony reviewed
I just have a few more comments, otherwise, LGTM

2023-01-09 13:36 UTC, TheArcaneBrony commented on docs/setup/server/index.md
> +If all went according to plan, you can now access your new Fosscord instance at [http://localhost:3001](http://localhost:3001)! Congrats!
One solution would be to add something along the lines of uh..
> If you set up your server remotely, use `curl` on the server to verify this, and look into setting up a reverse proxy.

2023-01-09 13:36 UTC, TheArcaneBrony commented on docs/setup/server/reverseProxy.md
> +
UPDATE: point out you can find it by checking what directories exist.

2023-01-09 13:36 UTC, TheArcaneBrony commented on docs/setup/server/security/regTokens.md
> +To create a registration token, send a GET request to `/auth/generate-registration-tokens/` as an account with `OPERATOR` [rights](rights.md)
arguments?
- `count`<int=1>: amount of registration tokens to generate
- `plain`<bool=false>: return as newline separated instead of json
- `include_url`<bool=false>: prefix tokens with url to register page

2023-01-09 13:36 UTC, TheArcaneBrony commented on docs/setup/server/security/rights.md
> +| `OPERATOR`                | 1 << 0  | All rights                                                                                                                                            |
iirc we are limited to 64 bits here. We're already at 40+, so we might have to split rights up into multiple fields.

2023-01-10 13:26 UTC, merged