Documentation for fosscord mail
fosscord/fosscord-docs pull request #56
Opened 2023-02-25 09:59 UTC by MaddyUnderStars

https://github.com/fosscord/fosscord-server/pull/965

2023-02-25 22:30 UTC, TheArcaneBrony commented on docs/setup/server/email.md
> +    | email_mailjey_apiSecret | string | Mailjet API secret |
Mailjey?

2023-02-25 22:35 UTC, Puyodead1 requested changes
also, mention that the `general_correspondenceEmail` configuration setting needs to be set to the "from" address

2023-02-25 22:35 UTC, Puyodead1 commented on docs/setup/server/email.md
> +| `{ipAddress}`            | The IP address that requested this email                  |
This is incorrect, the IP/location related placeholders are for the "New location detected" emails (which are currently unimplemented). However, including the IP/location of the user that triggered the email could be added.

2023-02-25 22:49 UTC, Puyodead1 commented on docs/setup/server/email.md
> +    | email_mailjey_apiSecret | string | Mailjet API secret |
lol, I made that typo all the time when I was writing the server PR

2023-02-26 00:13 UTC, Puyodead1 approved these changes

2023-02-26 03:15 UTC, merged